name: Secure Docker Build with SBOM and Vulnerability Scanning

on:
  push:
    branches: [ "master" ]
    paths:
      - 'Dockerfile'
      - 'seccomp.json'
      - '.github/workflows/build-and-sbom.yml'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'Dockerfile'
      - 'seccomp.json'
      - '.github/workflows/build-and-sbom.yml'

env:
  IMAGE_NAME: jq-secure-image
  IMAGE_TAG: latest
  REGISTRY: ghcr.io

jobs:
  secure-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write # For SARIF uploads

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for SBOM to detect git info

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # This step sets the FULL_IMAGE_REF variable in the GitHub Actions environment
      # so it can be used by subsequent steps in this job. This resolves the 'env' context error.
      - name: Set FULL_IMAGE_REF Variable
        run: echo "FULL_IMAGE_REF=${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}" >> $GITHUB_ENV

      - name: Build and Push
        uses: docker/build-push-action@v5
        id: build-push
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.FULL_IMAGE_REF }}
          push: ${{ github.event_name == 'push' }}
          provenance: true
          sbom: true
          seccomp: ./seccomp.json
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=image,name=${{ env.FULL_IMAGE_REF }},push=true

      - name: Verify Image Before SBOM
        run: |
          docker pull ${{ env.FULL_IMAGE_REF }}

      # Explicitly install and run Syft CLI to avoid anchore/syft-action download issues.
      # This method is more robust against 'Missing download info' errors for specific actions.
      - name: Install Syft CLI
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate SBOM with Syft CLI
        run: |
          syft ${{ env.FULL_IMAGE_REF }} -o spdx-json > sbom.spdx.json

      # Explicitly install and run Trivy CLI to avoid aquasecurity/trivy/main/contrib/install.sh.
      # This is the most robust approach given the persistent action fetching errors.
      - name: Install Trivy CLI
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Run Trivy Vulnerability Scan with CLI
        run: |
          trivy image --format sarif --severity CRITICAL,HIGH --ignore-unfixed --vuln-type os,library ${{ env.FULL_IMAGE_REF }} > trivy-results.sarif

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif

      - name: Docker Scout Analysis
        if: always() # Run this step even if previous steps fail
        uses: docker/scout-action@v1
        with:
          image: ${{ env.FULL_IMAGE_REF }}
          command: cve # REQUIRED: Specify the command for Docker Scout (e.g., 'cve' for vulnerabilities).
          output: summary
          severity: high,critical
          # Use a single Docker Hub Personal Access Token for authentication.
          # Ensure you have a GitHub secret named DOCKER_HUB_PAT containing your Docker Hub PAT.
          # This 'token' input is the primary method for authentication with Docker Scout.
          token: ${{ secrets.DOCKER_HUB_PAT }}

      - name: Archive outputs
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            sbom.spdx.json
            trivy-results.sarif
          retention-days: 7