name: Build Secure jq Image and Generate SBOM

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # If you intend to push the image to GitHub Container Registry

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry (if needed)
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        tags: ghcr.io/${{ github.repository_owner }}/secure-jq:latest # Replace with your desired registry/tag

    - name: Generate SBOM
      run: |
        docker run --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock secure-jq:latest > /dev/null # Ensure the image is built locally
        docker run --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock anchore/syft:latest ghcr.io/${{ github.repository_owner }}/secure-jq:latest -o spdx-json > sbom/sbom.spdx.json
        echo "SBOM generated: sbom/sbom.spdx.json"

    - name: Upload SBOM as artifact
      uses: actions/upload-artifact@v4
      with:
        name: sbom
        path: sbom/sbom.spdx.json
